spring:
    application:
        name: server
    datasource:
        url: jdbc:mysql://localhost:3306/TicTacToe?allowPublicKeyRetrieval=true&useSSL=false
        username: root 
        password: root
security:
    jwt:
        secret:
            yb7ZwGe3DWNp8yFvThZ+vYc9GVVSwz6+jFhmsHC/5p4=
        lifetime:
            900000
    refresh:
        lifetime:
            2147483647